export const ganaderos = [
  {
    name: "Jose Wilmer Garzon Portuguez",
    id: 10693024272,
    ruta: "porvenir",
    promedio: 11,
  },
  {
    name: "Maria Johana Rodriguez Rodrigu",
    id: 20645971,
    ruta: "porvenir",
    promedio: 12,
  },
  {
    name: "Sonia Dolores Cifuentes Rodrig",
    id: 20644886,
    ruta: "porvenir",
    promedio: 13,
  },
  {
    name: "Javier Acosta Velasquez",
    id: 3056526,
    ruta: "porvenir",
    promedio: 14,
  },
  {
    name: "Guillermo Gonzalez Sepulveda",
    id: 3056441,
    ruta: "porvenir",
    promedio: 15,
  },
  {
    name: "Yamid Danilo Cortes Reyes",
    id: 1069302294,
    ruta: "porvenir",
    promedio: 16,
  },
  { name: "Qualis Lac Sas", id: 901485261, ruta: "porvenir", promedio: 17 },
  { name: "Ines Padilla Lozano", id: 43745037, ruta: "porvenir", promedio: 18 },
  {
    name: "Nestor Javier Venegaz Linarez",
    id: 11232431,
    ruta: "porvenir",
    promedio: 19,
  },
  {
    name: "Juan Javier Urrego Acosta",
    id: 80377986,
    ruta: "porvenir",
    promedio: 20,
  },
  { name: "Jairo Diaz Zambrano", id: 3055862, ruta: "porvenir", promedio: 21 },
  {
    name: "Weismar Garcia Chitiva",
    id: 294979,
    ruta: "porvenir",
    promedio: 22,
  },
  {
    name: "Jose De Jesus Tovar Quinche",
    id: 3054900,
    ruta: "porvenir",
    promedio: 23,
  },
  {
    name: "Diogenes Ramirez Parra",
    id: 83239119,
    ruta: "porvenir",
    promedio: 24,
  },
  {
    name: "Gabriel Avellaneda Rueda",
    id: 17071352,
    ruta: "porvenir",
    promedio: 25,
  },
  {
    name: "Cristian Ferney Beltran Medell",
    id: 1003747023,
    ruta: "porvenir",
    promedio: 26,
  },
  {
    name: "Angel Alexander Rojas Rojas",
    id: 79988686,
    ruta: "porvenir",
    promedio: 27,
  },
  {
    name: "Diana Patricia Ramos Gantiva",
    id: 52848779,
    ruta: "porvenir",
    promedio: 28,
  },
];
