export const ganaderos = [
  {
    name: "Jose Wilmer Garzon Portuguez",
    id: 10693024272,
    ruta: "1",
    promedio: 11,
  },
  {
    name: "Maria Johana Rodriguez Rodrigu",
    id: 20645971,
    ruta: "1",
    promedio: 12,
  },
  {
    name: "Sonia Dolores Cifuentes Rodrig",
    id: 20644886,
    ruta: "1",
    promedio: 13,
  },
  {
    name: "Javier Acosta Velasquez",
    id: 3056526,
    ruta: "1",
    promedio: 14,
  },
  {
    name: "Guillermo Gonzalez Sepulveda",
    id: 3056441,
    ruta: "1",
    promedio: 15,
  },
  {
    name: "Yamid Danilo Cortes Reyes",
    id: 1069302294,
    ruta: "1",
    promedio: 16,
  },
  { name: "Qualis Lac Sas", id: 901485261, ruta: "1", promedio: 17 },
  { name: "Ines Padilla Lozano", id: 43745037, ruta: "1", promedio: 18 },
  {
    name: "Nestor Javier Venegaz Linarez",
    id: 11232431,
    ruta: "1",
    promedio: 19,
  },
  {
    name: "Juan Javier Urrego Acosta",
    id: 80377986,
    ruta: "1",
    promedio: 20,
  },
  { name: "Jairo Diaz Zambrano", id: 3055862, ruta: "1", promedio: 21 },
  {
    name: "Weismar Garcia Chitiva",
    id: 294979,
    ruta: "1",
    promedio: 22,
  },
  {
    name: "Jose De Jesus Tovar Quinche",
    id: 3054900,
    ruta: "1",
    promedio: 23,
  },
  {
    name: "Diogenes Ramirez Parra",
    id: 83239119,
    ruta: "1",
    promedio: 24,
  },
  {
    name: "Gabriel Avellaneda Rueda",
    id: 17071352,
    ruta: "1",
    promedio: 25,
  },
  {
    name: "Cristian Ferney Beltran Medell",
    id: 1003747023,
    ruta: "1",
    promedio: 26,
  },
  {
    name: "Angel Alexander Rojas Rojas",
    id: 79988686,
    ruta: "1",
    promedio: 27,
  },
  {
    name: "Diana Patricia Ramos Gantiva",
    id: 52848779,
    ruta: "1",
    promedio: 28,
  },
];

export const listRoutes = [
  { id: "1", name: "Porvenir" },
  { id: "2", name: "San Carlos" },
  { id: "3", name: "Rosal" },
  { id: "4", name: "San Jorge" },
  { id: "5", name: "San Marcos" },
  { id: "6", name: "Alfarero" },
  { id: "7", name: "Rafa SAS" },
  { id: "8", name: "Choachi" },
  { id: "9", name: "Almeciga" },
  { id: "10", name: "Pinalact" },
  { id: "11", name: "Aquileo" },
  { id: "12", name: "Sopo" },
  { id: "13", name: "Ricolacteos" },
  { id: "14", name: "Fasalact" },
  { id: "15", name: "Avella" },
  { id: "16", name: "Choconta" },
  { id: "17", name: "Asolesam" },
  { id: "18", name: "Caleras" },
];

export const conductores = [
  { id: "1", name: "Adrian", ruta: "1", placas: "WGZ149" },
  { id: "2", name: "Edgar", ruta: "2", placas: "WGZ149" },
  { id: "3", name: "Aldemar", ruta: "4", placas: "WLK629" },
  { id: "4", name: "Wilson", ruta: "3", placas: "USV031" },
  { id: "5", name: "Manuel", ruta: "5", placas: "" },
  { id: "6", name: "Danilo", ruta: "2", placas: "TLO684" },
  { id: "7", name: "Dayan", ruta: "5", placas: "" },
  { id: "8", name: "Octaviano", ruta: "17", placas: "" },
  { id: "9", name: "Planta", ruta: "18", placas: "PLANTA" },
];
