export const ganaderosLOCAL = [
  {
    nombre: "Jose Wilmer Garzon Portuguez",
    documento: 10693024272,
    ruta: "1",
    promedio: 11,
  },
  {
    nombre: "Maria Johana Rodriguez Rodrigu",
    documento: 20645971,
    ruta: "1",
    promedio: 12,
  },
  {
    nombre: "Sonia Dolores Cifuentes Rodrig",
    documento: 20644886,
    ruta: "1",
    promedio: 13,
  },
  {
    nombre: "Javier Acosta Velasquez",
    documento: 3056526,
    ruta: "1",
    promedio: 14,
  },
  {
    nombre: "Guillermo Gonzalez Sepulveda",
    documento: 3056441,
    ruta: "1",
    promedio: 15,
  },
  {
    nombre: "Yamdocumento Danilo Cortes Reyes",
    documento: 1069302294,
    ruta: "1",
    promedio: 16,
  },
  { nombre: "Qualis Lac Sas", documento: 901485261, ruta: "1", promedio: 17 },
  {
    nombre: "Ines Padilla Lozano",
    documento: 43745037,
    ruta: "1",
    promedio: 18,
  },
  {
    nombre: "Nestor Javier Venegaz Linarez",
    documento: 11232431,
    ruta: "1",
    promedio: 19,
  },
  {
    nombre: "Juan Javier Urrego Acosta",
    documento: 80377986,
    ruta: "1",
    promedio: 20,
  },
  {
    nombre: "Jairo Diaz Zambrano",
    documento: 3055862,
    ruta: "1",
    promedio: 21,
  },
  {
    nombre: "Weismar Garcia Chitiva",
    documento: 294979,
    ruta: "1",
    promedio: 22,
  },
  {
    nombre: "Jose De Jesus Tovar Quinche",
    documento: 3054900,
    ruta: "1",
    promedio: 23,
  },
  {
    nombre: "Diogenes Ramirez Parra",
    documento: 83239119,
    ruta: "1",
    promedio: 24,
  },
  {
    nombre: "Gabriel Avellaneda Rueda",
    documento: 17071352,
    ruta: "1",
    promedio: 25,
  },
  {
    nombre: "Cristian Ferney Beltran Medell",
    documento: 1003747023,
    ruta: "1",
    promedio: 26,
  },
  {
    nombre: "Angel Alexander Rojas Rojas",
    documento: 79988686,
    ruta: "1",
    promedio: 27,
  },
  {
    nombre: "Diana Patricia Ramos Gantiva",
    documento: 52848779,
    ruta: "1",
    promedio: 28,
  },
];

export const rutasLOCAL = [
  { id: "1", nombre: "Porvenir" },
  { id: "2", nombre: "San Carlos" },
  { id: "3", nombre: "Rosal" },
  { id: "4", nombre: "San Jorge" },
  { id: "5", nombre: "San Marcos" },
  { id: "6", nombre: "Alfarero" },
  { id: "7", nombre: "Rafa SAS" },
  { id: "8", nombre: "Choachi" },
  { id: "9", nombre: "Almeciga" },
  { id: "10", nombre: "Pinalact" },
  { id: "11", nombre: "Aquileo" },
  { id: "12", nombre: "Sopo" },
  { id: "13", nombre: "Ricolacteos" },
  { id: "14", nombre: "Fasalact" },
  { id: "15", nombre: "Avella" },
  { id: "16", nombre: "Choconta" },
  { id: "17", nombre: "Asolesam" },
  { id: "18", nombre: "Caleras" },
];

export const conductoresLOCAL = [
  {
    id: "5",
    nombre: "Adrian----",
    placa: "WGZ149",
    ruta: "1",
    rutas: "porvenir",
  },
  { id: "6", nombre: "Edgar", placa: "WGZ149", ruta: "2", rutas: "san carlos" },
  {
    id: "7",
    nombre: "Aldemar",
    placa: "WLK629",
    ruta: "4",
    rutas: "san jorge",
  },
  { id: "8", nombre: "Wilson", placa: "USV031", ruta: "3", rutas: "rosal" },
  { id: "9", nombre: "Manuel", placa: "", ruta: "5", rutas: "san marcos" },
  {
    id: "10",
    nombre: "Danilo",
    placa: "TLO684",
    ruta: "2",
    rutas: "san carlos",
  },
  { id: "11", nombre: "Dayan", placa: "", ruta: "5", rutas: "san marcos" },
];

export const usuariosLOCAL = [
  { id: "5", usuario: "adrian", password: "adrian0000", tipo: 1 },
  { id: "6", usuario: "edgar", password: "edgar0000", tipo: 1 },
  { id: "7", usuario: "aldemar", password: "aldemar0000", tipo: 1 },
  { id: "8", usuario: "wilson", password: "wilson0000", tipo: 1 },
  { id: "9", usuario: "manuel", password: "manuel0000", tipo: 1 },
  { id: "10", usuario: "danilo", password: "danilo0000", tipo: 1 },
  { id: "11", usuario: "dayan", password: "dayan0000", tipo: 1 },
];
